# Generated by Django 4.2 on 2023-10-04 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=1)),
                ('seconds_per_turn', models.IntegerField(default=900)),
            ],
        ),
        migrations.CreateModel(
            name='QueuedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('queue_position', models.IntegerField()),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('playing_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('finishing_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shqueue.gamequeue')),
                ('queued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_by', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
